import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="h-screen grid place-items-center m-auto">
      <Head>
        <title>McNaughtans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src={"/mcnaughtans.png"}
        width={300}
        height={100}
        className="object-cover"
      />
      <div className="rounded-lg bg-[#00CCBB] p-10 text-white text-center text-xl font-bold">
        Your Password was changed
      </div>
    </div>
  );
};

export default Home;
